#!/usr/bin/env node
/* =============================================================================
 * Remember Them - import a Drive folder listing into the examples data
 * -----------------------------------------------------------------------------
 *   node tools/import-drive.js tools/drive-listing.json
 *
 * Reads a listing of the Drive subfolders and the image files inside them,
 * matches each folder to a memorial type using tools/drive-folders.json, and
 * rewrites assets/data/examples.js.
 *
 * It only ever writes assets/data/examples.js. catalog.js - which holds the
 * designer's own configuration - is never touched by an import.
 *
 * The listing it expects:
 *
 *   {
 *     "folders": [
 *       { "name": "Uprights", "id": "1abc...",
 *         "files": [ { "name": "smith-proof.jpg", "id": "1xyz...",
 *                      "mimeType": "image/jpeg" } ] }
 *     ]
 *   }
 *
 * Image files themselves are downloaded separately into
 * assets/img/<category-id>/. See docs/DRIVE-SYNC.md.
 * =========================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const MAP_FILE = path.join(ROOT, 'tools', 'drive-folders.json');
const OUT_FILE = path.join(ROOT, 'assets', 'data', 'examples.js');

const IMAGE_TYPES = /^image\/(jpeg|jpg|png|webp|gif|heic|tiff)$/i;
const IMAGE_EXT = /\.(jpe?g|png|webp|gif|heic|tiff?)$/i;

function die(msg) {
  console.error('import-drive: ' + msg);
  process.exit(1);
}

/* A file name a person typed becomes a file name a web server can serve. */
function slug(name) {
  return name
    .replace(IMAGE_EXT, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'image';
}

function extOf(name, mimeType) {
  const m = name.match(IMAGE_EXT);
  if (m) return m[0].toLowerCase().replace('.jpeg', '.jpg');
  if (/png/i.test(mimeType)) return '.png';
  if (/webp/i.test(mimeType)) return '.webp';
  return '.jpg';
}

function main() {
  const listingPath = process.argv[2];
  if (!listingPath) die('usage: node tools/import-drive.js <listing.json>');
  if (!fs.existsSync(listingPath)) die('no such listing file: ' + listingPath);

  const listing = JSON.parse(fs.readFileSync(listingPath, 'utf8'));
  const config = JSON.parse(fs.readFileSync(MAP_FILE, 'utf8'));

  /* folder name (lowercased) -> categoryId */
  const byName = new Map();
  const byId = new Map();
  config.map.forEach(function (row) {
    if (row.folder) byName.set(String(row.folder).trim().toLowerCase(), row.categoryId);
    if (row.id) byId.set(row.id, row.categoryId);
  });

  const out = {};
  config.map.forEach(function (row) {
    out[row.categoryId] = { driveFolder: null, examples: [] };
  });

  const unmatched = [];
  let imageCount = 0;

  (listing.folders || []).forEach(function (folder) {
    const categoryId = byId.get(folder.id) ||
      byName.get(String(folder.name || '').trim().toLowerCase());

    if (!categoryId) { unmatched.push(folder.name); return; }
    if (!out[categoryId]) out[categoryId] = { driveFolder: null, examples: [] };

    out[categoryId].driveFolder = { name: folder.name, id: folder.id };

    const seen = new Set();
    (folder.files || [])
      .filter(function (f) {
        return IMAGE_TYPES.test(f.mimeType || '') || IMAGE_EXT.test(f.name || '');
      })
      .forEach(function (f, i) {
        /* Two photos in one folder can share a name. Keep both. */
        let base = slug(f.name);
        let name = base;
        let n = 2;
        while (seen.has(name)) { name = base + '-' + n++; }
        seen.add(name);

        const file = name + extOf(f.name, f.mimeType || '');
        out[categoryId].examples.push({
          id: categoryId + '-' + String(i + 1).padStart(3, '0'),
          image: 'assets/img/' + categoryId + '/' + file,
          driveId: f.id,
          driveName: f.name,
          /* Alt text has to describe the memorial, and must never carry a real
           * family's name. Written by hand after import - see DRIVE-SYNC.md. */
          alt: 'TODO: describe this memorial without naming anyone.',
          configuration: null,
          granite: null,
          shape: null,
          size: null,
          features: [],
          notes: null
        });
        imageCount++;
      });
  });

  const header =
`/* =============================================================================
 * Remember Them - reference examples
 * -----------------------------------------------------------------------------
 * GENERATED by tools/import-drive.js. Re-running the import overwrites this
 * file, so any alt text, granite name or size you write by hand should be
 * carried across - see docs/DRIVE-SYNC.md before you re-import.
 *
 * These are examples of work, not products. No prices, no inventory.
 * =========================================================================== */

window.RT_EXAMPLES = {
  version: 1,
  source: ${JSON.stringify(config.source, null, 2).replace(/\n/g, '\n  ')},
  categories: ${JSON.stringify(out, null, 2).replace(/\n/g, '\n  ')}
};
`;

  fs.writeFileSync(OUT_FILE, header);

  console.log('Wrote ' + path.relative(ROOT, OUT_FILE));
  console.log('  ' + imageCount + ' images across ' +
    Object.keys(out).filter(function (k) { return out[k].examples.length; }).length +
    ' memorial types');

  const empty = Object.keys(out).filter(function (k) { return !out[k].examples.length; });
  if (empty.length) console.log('  no images yet for: ' + empty.join(', '));
  if (unmatched.length) {
    console.log('');
    console.log('  These Drive folders matched no memorial type and were skipped:');
    unmatched.forEach(function (n) { console.log('    - ' + n); });
    console.log('  Add them to the "map" in tools/drive-folders.json.');
  }
}

main();
